title: Deepanshu Kartikey
description: Performance Engineer · Linux Kernel Contributor
url: "https://deepanshukartikey.dev"
author: Deepanshu Kartikey
email: kartikey406@gmail.com

github: https://github.com/deepanshuclickpost
linkedin: https://www.linkedin.com/in/deepanshu-kartikey-16024498/
lkml: https://lkml.kernel.org

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
baseurl: "/deepanshukartikey.dev"
